# Generated by Django 6.0.6 on 2026-06-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.CharField(choices=[('saved', 'Избранное'), ('private', 'Личный чат')], default='private', max_length=20),
        ),
    ]
