# Generated by Django 6.0.6 on 2026-06-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_profile_avatar_url_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
